[build]
  command = "npm run build"  # Comando para construir el proyecto
  publish = ".output/public"  # Directorio de publicaci칩n

# Configuraci칩n para SSR utilizando Edge Functions
[[edge_functions]]
  path = "/*"
  function = "server"  # Esto hace que cualquier ruta sea manejada por SSR

# Variables de entorno
[build.environment]
  NODE_VERSION = "18.x"  # Versi칩n de Node.js que Netlify usar치 para construir el proyecto
  NITRO_PRESET = "netlify"  # Define el preset de Nitro para Netlify
